### ISSUE TITLE
Error: A tree hydrated but some attributes of the server rendered HTML didn't match the client properties.

### ISSUE THREAD

**Issue by 1chooo** [1chooo/vcard#623]
Error: A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

https://react.dev/link/hydration-mismatch

  ...
    <HotReload assetPrefix="">
      <ReactDevOverlay state={{nextId:1, ...}} dispatcher={{...}}>
        <DevRootNotFoundBoundary>
          <NotFoundBoundary notFound={<NotAllowedRootNotFoundError>}>
            <NotFoundErrorBoundary pathname="/" notFound={<NotAllowedRootNotFoundError>} notFoundStyles={undefined} ...>
              <RedirectBoundary>
                <RedirectErrorBoundary router={{...}}>
                  <Head>
                  <link>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <script>
                  <RootLayout>
                    <html lang="en" className="roboto_f3a...">
                      <WebVitals>
                      <body
-                       data-new-gr-c-s-check-loaded="14.1213.0"
-                       data-gr-ext-installed=""
                      >
                      ...
                  ...
        ...

    at createUnhandledError (http://localhost:3000/_next/static/chunks/08b5e_next_dist_client_9bb038._.js:744:19)
    at handleClientError (http://localhost:3000/_next/static/chunks/08b5e_next_dist_client_9bb038._.js:905:98)
    at console.error (http://localhost:3000/_next/static/chunks/08b5e_next_dist_client_9bb038._.js:1036:56)
    at emitPendingHydrationWarnings (http://localhost:3000/_next/static/chunks/08b5e_next_dist_compiled_react-dom_1f56dc._.js:2766:103)
    at completeWork (http://localhost:3000/_next/static/chunks/08b5e_next_dist_compiled_react-dom_1f56dc._.js:7226:102)
    at runWithFiberInDEV (http://localhost:3000/_next/static/chunks/08b5e_next_dist_compiled_react-dom_1f56dc._.js:631:20)
    at completeUnitOfWork (http://localhost:3000/_next/static/chunks/08b5e_next_dist_compiled_react-dom_1f56dc._.js:7996:23)
    at performUnitOfWork (http://localhost:3000/_next/static/chunks/08b5e_next_dist_compiled_react-dom_1f56dc._.js:7938:28)
    at workLoopConcurrent (http://localhost:3000/_next/static/chunks/08b5e_next_dist_compiled_react-dom_1f56dc._.js:7932:58)
    at renderRootConcurrent (http://localhost:3000/_next/static/chunks/08b5e_next_dist_compiled_react-dom_1f56dc._.js:7914:71)
    at performWorkOnRoot (http://localhost:3000/_next/static/chunks/08b5e_next_dist_compiled_react-dom_1f56dc._.js:7553:112)
    at performWorkOnRootViaSchedulerTask (http://localhost:3000/_next/static/chunks/08b5e_next_dist_compiled_react-dom_1f56dc._.js:8387:9)
    at MessagePort.performWorkUntilDeadline (http://localhost:3000/_next/static/chunks/08b5e_next_dist_compiled_107ce8._.js:2348:64)

**Comment by 1chooo** [comment]
when we remove the grammerly browser extension; this error is missing!
